M48
; DRILL file {KiCad 9.0.4} date 2025-09-16T01:10:01+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-16T01:10:01+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.200
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C0.300
%
G90
G05
T1
X154.11Y-66.75
X154.11Y-67.75
X154.11Y-68.75
T2
X148.0Y-67.5
X158.5Y-65.0
X164.0Y-70.5
M30
